server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liga
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true
    hikari:
        maximum-pool-size: 10
  #  schema: classpath:init/schema.sql
 #   data: classpath:init/data.sql
  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: true
mybatis:
  configuration:
    mapUnderscoreToCamelCase : true